# Use a file-based DuckDB instead of in-memory
duckdb_conn = duckdb.connect(database='my_data.duckdb')

# Create tables for persistent storage
duckdb_conn.execute("""
    CREATE SCHEMA IF NOT EXISTS metadata;
    CREATE TABLE IF NOT EXISTS metadata.query_config (
        query_id INTEGER PRIMARY KEY,
        sql_text VARCHAR,
        instance_name VARCHAR,
        target_table VARCHAR,
        db_type VARCHAR,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS metadata.runs (
        run_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        query_id INTEGER,
        status VARCHAR,
        rows_affected INTEGER,
        execution_time_ms INTEGER,
        run_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(query_id) REFERENCES metadata.query_config(query_id)
    );
""")